# Generated by Django 5.0.3 on 2024-05-13 07:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=16)),
                ('zip', models.CharField(max_length=16)),
                ('county', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('VIN', models.CharField(max_length=17, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='crmapp.address')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='crmapp.address')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='crmapp.address')),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='crmapp.buildingtype')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='crmapp.address')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=255)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.agency')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.agent')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='crmapp.building')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='crmapp.customer')),
                ('policy_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='crmapp.policytype')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='crmapp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='crmapp.policy')),
            ],
            options={
                'unique_together': {('customer', 'policy')},
            },
        ),
    ]
